### ISSUE TITLE
Error to running inference after training the model

### ISSUE THREAD

**Issue by wirayogantara** [lojzezust/WaSR-T#3]
Hi,
i had the problem to running the inference after trying to train your models, use the train.py script following your instruction. 

this the error message:
oprek@1dd801f98bc4:~/Wasr/WaSR-T$ python predict_sequential.py --sequence-dir examples/sequence --hist-len 5 --weights output/models/my_wasr_v36/model.pth --output-dir output/predictions --resize none --fp16 --gpu -1
Namespace(fp16=True, gpus='-1', hist_len=5, output_dir='output/predictions', resize=[None], sequence_dir='examples/sequence', weights='output/models/my_wasr_v36/model.pth')
Traceback (most recent call last):
  File "predict_sequential.py", line 100, in <module>
    main()
  File "predict_sequential.py", line 96, in main
    run_inference(args)
  File "predict_sequential.py", line 79, in run_inference
    state_dict = load_weights(args.weights)
  File "/home/oprek/Wasr/WaSR-T/wasr_t/utils.py", line 34, in load_weights
    if 'model' in state_dict:
TypeError: argument of type 'WaSRT' is not iterable

**Comment by lojzezust** [comment]
Please try to load the weights from the log directory instead. For example: `output/logs/my_wasr/version_36/checkpoints/last.ckpt`.

**Comment by wirayogantara** [comment]
Thank you its work
